# Generated by Django 5.2.7 on 2025-10-17 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='teacher',
        ),
    ]
